apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wndudwns0028/my-starter-kit
    targetRevision: main
    path: ci-cd/argocd/apps    # 개별 Application 파일들을 이 디렉토리에 추가
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
